# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/grpc/proto/fixture/fixture.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from app.grpc.proto.competition import competition_pb2 as app_dot_grpc_dot_proto_dot_competition_dot_competition__pb2
from app.grpc.proto.season import season_pb2 as app_dot_grpc_dot_proto_dot_season_dot_season__pb2
from app.grpc.proto.team import team_pb2 as app_dot_grpc_dot_proto_dot_team_dot_team__pb2
from app.grpc.proto.venue import venue_pb2 as app_dot_grpc_dot_proto_dot_venue_dot_venue__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/grpc/proto/fixture/fixture.proto',
  package='statistico_data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$app/grpc/proto/fixture/fixture.proto\x12\x0fstatistico_data\x1a\x1egoogle/protobuf/wrappers.proto\x1a,app/grpc/proto/competition/competition.proto\x1a\"app/grpc/proto/season/season.proto\x1a\x1e\x61pp/grpc/proto/team/team.proto\x1a app/grpc/proto/venue/venue.proto\"6\n\x10\x44\x61teRangeRequest\x12\x11\n\tdate_from\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61te_to\x18\x02 \x01(\t\"$\n\x0e\x46ixtureRequest\x12\x12\n\nfixture_id\x18\x01 \x01(\x03\"\xb0\x02\n\x07\x46ixture\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x31\n\x0b\x63ompetition\x18\x02 \x01(\x0b\x32\x1c.statistico_data.Competition\x12\'\n\x06season\x18\x03 \x01(\x0b\x32\x17.statistico_data.Season\x12(\n\thome_team\x18\x04 \x01(\x0b\x32\x15.statistico_data.Team\x12(\n\taway_team\x18\x05 \x01(\x0b\x32\x15.statistico_data.Team\x12%\n\x05venue\x18\x06 \x01(\x0b\x32\x16.statistico_data.Venue\x12/\n\nreferee_id\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x11\n\tdate_time\x18\x08 \x01(\x03\x32\xad\x01\n\x0e\x46ixtureService\x12O\n\x0cListFixtures\x12!.statistico_data.DateRangeRequest\x1a\x18.statistico_data.Fixture\"\x00\x30\x01\x12J\n\x0b\x46ixtureByID\x12\x1f.statistico_data.FixtureRequest\x1a\x18.statistico_data.Fixture\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,app_dot_grpc_dot_proto_dot_competition_dot_competition__pb2.DESCRIPTOR,app_dot_grpc_dot_proto_dot_season_dot_season__pb2.DESCRIPTOR,app_dot_grpc_dot_proto_dot_team_dot_team__pb2.DESCRIPTOR,app_dot_grpc_dot_proto_dot_venue_dot_venue__pb2.DESCRIPTOR,])




_DATERANGEREQUEST = _descriptor.Descriptor(
  name='DateRangeRequest',
  full_name='statistico_data.DateRangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_from', full_name='statistico_data.DateRangeRequest.date_from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_to', full_name='statistico_data.DateRangeRequest.date_to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=291,
)


_FIXTUREREQUEST = _descriptor.Descriptor(
  name='FixtureRequest',
  full_name='statistico_data.FixtureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fixture_id', full_name='statistico_data.FixtureRequest.fixture_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=329,
)


_FIXTURE = _descriptor.Descriptor(
  name='Fixture',
  full_name='statistico_data.Fixture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='statistico_data.Fixture.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='competition', full_name='statistico_data.Fixture.competition', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='season', full_name='statistico_data.Fixture.season', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='home_team', full_name='statistico_data.Fixture.home_team', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='away_team', full_name='statistico_data.Fixture.away_team', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='venue', full_name='statistico_data.Fixture.venue', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referee_id', full_name='statistico_data.Fixture.referee_id', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_time', full_name='statistico_data.Fixture.date_time', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=636,
)

_FIXTURE.fields_by_name['competition'].message_type = app_dot_grpc_dot_proto_dot_competition_dot_competition__pb2._COMPETITION
_FIXTURE.fields_by_name['season'].message_type = app_dot_grpc_dot_proto_dot_season_dot_season__pb2._SEASON
_FIXTURE.fields_by_name['home_team'].message_type = app_dot_grpc_dot_proto_dot_team_dot_team__pb2._TEAM
_FIXTURE.fields_by_name['away_team'].message_type = app_dot_grpc_dot_proto_dot_team_dot_team__pb2._TEAM
_FIXTURE.fields_by_name['venue'].message_type = app_dot_grpc_dot_proto_dot_venue_dot_venue__pb2._VENUE
_FIXTURE.fields_by_name['referee_id'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT64VALUE
DESCRIPTOR.message_types_by_name['DateRangeRequest'] = _DATERANGEREQUEST
DESCRIPTOR.message_types_by_name['FixtureRequest'] = _FIXTUREREQUEST
DESCRIPTOR.message_types_by_name['Fixture'] = _FIXTURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DateRangeRequest = _reflection.GeneratedProtocolMessageType('DateRangeRequest', (_message.Message,), dict(
  DESCRIPTOR = _DATERANGEREQUEST,
  __module__ = 'app.grpc.proto.fixture.fixture_pb2'
  # @@protoc_insertion_point(class_scope:statistico_data.DateRangeRequest)
  ))
_sym_db.RegisterMessage(DateRangeRequest)

FixtureRequest = _reflection.GeneratedProtocolMessageType('FixtureRequest', (_message.Message,), dict(
  DESCRIPTOR = _FIXTUREREQUEST,
  __module__ = 'app.grpc.proto.fixture.fixture_pb2'
  # @@protoc_insertion_point(class_scope:statistico_data.FixtureRequest)
  ))
_sym_db.RegisterMessage(FixtureRequest)

Fixture = _reflection.GeneratedProtocolMessageType('Fixture', (_message.Message,), dict(
  DESCRIPTOR = _FIXTURE,
  __module__ = 'app.grpc.proto.fixture.fixture_pb2'
  # @@protoc_insertion_point(class_scope:statistico_data.Fixture)
  ))
_sym_db.RegisterMessage(Fixture)



_FIXTURESERVICE = _descriptor.ServiceDescriptor(
  name='FixtureService',
  full_name='statistico_data.FixtureService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=639,
  serialized_end=812,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListFixtures',
    full_name='statistico_data.FixtureService.ListFixtures',
    index=0,
    containing_service=None,
    input_type=_DATERANGEREQUEST,
    output_type=_FIXTURE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FixtureByID',
    full_name='statistico_data.FixtureService.FixtureByID',
    index=1,
    containing_service=None,
    input_type=_FIXTUREREQUEST,
    output_type=_FIXTURE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIXTURESERVICE)

DESCRIPTOR.services_by_name['FixtureService'] = _FIXTURESERVICE

# @@protoc_insertion_point(module_scope)
