version: '3.5'
services:

    grpc:
      image: joesweeny/statisticopredictor_grpc:$RELEASE
      ports:
        - "50051:50051"
      environment:
        DATA_SERVER_HOST: $DATA_SERVER_HOST
        DATA_SERVER_PORT: $DATA_SERVER_PORT
      tty: true
