version: '3'
services:

  console: &console
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    volumes:
      - .:/opt
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=15
      - DATA_SERVER_HOST=138.68.132.183
      - DATA_SERVER_PORT=50051

  grpc:
    <<: *console
    ports:
      - "50051:50051"
    command: ["python3", "-m", "compiler.grpc"]

  cron:
    <<: *console
    command: ["cron", "-f"]

  redis:
    image: 'redis'
