version: '3'
services:

  console: &console
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    networks:
      - statistico-data_default
      - statistico-odds-compiler_default
    volumes:
      - .:/opt
    tty: true
    environment:
      - DATA_SERVER_HOST=statistico-data-grpc
      - DATA_SERVER_PORT=50051
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=15

  grpc:
    <<: *console
    volumes:
      - .:/opt
    networks:
      - statistico-data_default
      - statistico-odds-compiler_default
    environment:
      - DATA_SERVER_HOST=statistico-data-grpc
      - DATA_SERVER_PORT=50051
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=15
    ports:
      - "50052:50052"
    command: ["python3", "-m", "compiler.grpc"]

  cron:
    <<: *console
    command: ["cron", "-f"]

  redis:
    image: 'redis'
    networks:
      - statistico-odds-compiler_default

networks:
  statistico-data_default:
    external: true
  statistico-odds-compiler_default:
    external: false