version: '3.5'
services:

    grpc:
      image: joesweeny/statisticopredictor_grpc:$RELEASE
      ports:
        - "50051:50051"
      tty: true
      command: ["python3", "./opt/app/grpc/server.py"]
