version: '3'
services:

  grpc:
    build:
      dockerfile: ./docker/grpc/Dockerfile
      context: ./
    volumes:
      - .:/opt
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=15
      - DATA_SERVER_HOST=138.68.132.183
      - DATA_SERVER_PORT=50051
    ports:
      - "50051:50051"


  console:
    build:
      dockerfile: ./docker/console/Dockerfile
      context: ./
    volumes:
      - .:/opt
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=15
      - DATA_SERVER_HOST=138.68.132.183
      - DATA_SERVER_PORT=50051

  redis:
    image: 'redis'
