version: '3.5'
services:

    grpc:
      image: joesweeny/statisticooddscompiler_grpc:$RELEASE
      ports:
        - "50051:50051"
      environment:
        DATA_SERVER_HOST: $DATA_SERVER_HOST
        DATA_SERVER_PORT: $DATA_SERVER_PORT
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_DATABASE: 0
      tty: true

    console:
      image: joesweeny/statisticooddscompiler_console:$RELEASE
      environment:
        DATA_SERVER_HOST: $DATA_SERVER_HOST
        DATA_SERVER_PORT: $DATA_SERVER_PORT
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_DATABASE: 0
      tty: true

    redis:
      image: 'redis'

    cron:
      image: joesweeny/statisticooddscompiler_cron:$RELEASE
      environment:
        DATA_SERVER_HOST: $DATA_SERVER_HOST
        DATA_SERVER_PORT: $DATA_SERVER_PORT
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_DATABASE: 0
