# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from compiler.grpc.proto.compiler import compiler_pb2 as compiler_dot_grpc_dot_proto_dot_compiler_dot_compiler__pb2


class CompilerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOverUnderGoalsForFixture = channel.unary_unary(
        '/prediction.CompilerService/GetOverUnderGoalsForFixture',
        request_serializer=compiler_dot_grpc_dot_proto_dot_compiler_dot_compiler__pb2.OverUnderRequest.SerializeToString,
        response_deserializer=compiler_dot_grpc_dot_proto_dot_compiler_dot_compiler__pb2.OverUnderGoalsResponse.FromString,
        )


class CompilerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOverUnderGoalsForFixture(self, request, context):
    """Returns a Over/Under goals compiler for a given fixture
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CompilerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOverUnderGoalsForFixture': grpc.unary_unary_rpc_method_handler(
          servicer.GetOverUnderGoalsForFixture,
          request_deserializer=compiler_dot_grpc_dot_proto_dot_compiler_dot_compiler__pb2.OverUnderRequest.FromString,
          response_serializer=compiler_dot_grpc_dot_proto_dot_compiler_dot_compiler__pb2.OverUnderGoalsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'prediction.CompilerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
