# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from compiler.grpc.proto.fixture import fixture_pb2 as compiler_dot_grpc_dot_proto_dot_fixture_dot_fixture__pb2


class FixtureServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListFixtures = channel.unary_stream(
        '/fixture.FixtureService/ListFixtures',
        request_serializer=compiler_dot_grpc_dot_proto_dot_fixture_dot_fixture__pb2.DateRangeRequest.SerializeToString,
        response_deserializer=compiler_dot_grpc_dot_proto_dot_fixture_dot_fixture__pb2.Fixture.FromString,
        )
    self.FixtureByID = channel.unary_unary(
        '/fixture.FixtureService/FixtureByID',
        request_serializer=compiler_dot_grpc_dot_proto_dot_fixture_dot_fixture__pb2.FixtureRequest.SerializeToString,
        response_deserializer=compiler_dot_grpc_dot_proto_dot_fixture_dot_fixture__pb2.Fixture.FromString,
        )


class FixtureServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListFixtures(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FixtureByID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FixtureServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListFixtures': grpc.unary_stream_rpc_method_handler(
          servicer.ListFixtures,
          request_deserializer=compiler_dot_grpc_dot_proto_dot_fixture_dot_fixture__pb2.DateRangeRequest.FromString,
          response_serializer=compiler_dot_grpc_dot_proto_dot_fixture_dot_fixture__pb2.Fixture.SerializeToString,
      ),
      'FixtureByID': grpc.unary_unary_rpc_method_handler(
          servicer.FixtureByID,
          request_deserializer=compiler_dot_grpc_dot_proto_dot_fixture_dot_fixture__pb2.FixtureRequest.FromString,
          response_serializer=compiler_dot_grpc_dot_proto_dot_fixture_dot_fixture__pb2.Fixture.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fixture.FixtureService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
