# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compiler/grpc/proto/compiler.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compiler/grpc/proto/compiler.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"compiler/grpc/proto/compiler.proto\x12\x05proto\"0\n\x0c\x45ventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x04\x12\x0e\n\x06market\x18\x02 \x01(\t\"J\n\x0b\x45ventMarket\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x04\x12\x0e\n\x06market\x18\x02 \x01(\t\x12\x19\n\x04odds\x18\x03 \x03(\x0b\x32\x0b.proto.Odds\"(\n\x04Odds\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x11\n\tselection\x18\x02 \x01(\t2R\n\x13OddsCompilerService\x12;\n\x0eGetEventMarket\x12\x13.proto.EventRequest\x1a\x12.proto.EventMarket\"\x00\x62\x06proto3'
)




_EVENTREQUEST = _descriptor.Descriptor(
  name='EventRequest',
  full_name='proto.EventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_id', full_name='proto.EventRequest.event_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='market', full_name='proto.EventRequest.market', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=93,
)


_EVENTMARKET = _descriptor.Descriptor(
  name='EventMarket',
  full_name='proto.EventMarket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_id', full_name='proto.EventMarket.event_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='market', full_name='proto.EventMarket.market', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='odds', full_name='proto.EventMarket.odds', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=169,
)


_ODDS = _descriptor.Descriptor(
  name='Odds',
  full_name='proto.Odds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='proto.Odds.price', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selection', full_name='proto.Odds.selection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=211,
)

_EVENTMARKET.fields_by_name['odds'].message_type = _ODDS
DESCRIPTOR.message_types_by_name['EventRequest'] = _EVENTREQUEST
DESCRIPTOR.message_types_by_name['EventMarket'] = _EVENTMARKET
DESCRIPTOR.message_types_by_name['Odds'] = _ODDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventRequest = _reflection.GeneratedProtocolMessageType('EventRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVENTREQUEST,
  '__module__' : 'compiler.grpc.proto.compiler_pb2'
  # @@protoc_insertion_point(class_scope:proto.EventRequest)
  })
_sym_db.RegisterMessage(EventRequest)

EventMarket = _reflection.GeneratedProtocolMessageType('EventMarket', (_message.Message,), {
  'DESCRIPTOR' : _EVENTMARKET,
  '__module__' : 'compiler.grpc.proto.compiler_pb2'
  # @@protoc_insertion_point(class_scope:proto.EventMarket)
  })
_sym_db.RegisterMessage(EventMarket)

Odds = _reflection.GeneratedProtocolMessageType('Odds', (_message.Message,), {
  'DESCRIPTOR' : _ODDS,
  '__module__' : 'compiler.grpc.proto.compiler_pb2'
  # @@protoc_insertion_point(class_scope:proto.Odds)
  })
_sym_db.RegisterMessage(Odds)



_ODDSCOMPILERSERVICE = _descriptor.ServiceDescriptor(
  name='OddsCompilerService',
  full_name='proto.OddsCompilerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=213,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEventMarket',
    full_name='proto.OddsCompilerService.GetEventMarket',
    index=0,
    containing_service=None,
    input_type=_EVENTREQUEST,
    output_type=_EVENTMARKET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ODDSCOMPILERSERVICE)

DESCRIPTOR.services_by_name['OddsCompilerService'] = _ODDSCOMPILERSERVICE

# @@protoc_insertion_point(module_scope)
