# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from compiler.grpc.proto import event_pb2 as compiler_dot_grpc_dot_proto_dot_event__pb2
from compiler.grpc.proto import requests_pb2 as compiler_dot_grpc_dot_proto_dot_requests__pb2


class EventServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FixtureEvents = channel.unary_unary(
                '/proto.EventService/FixtureEvents',
                request_serializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.FixtureRequest.SerializeToString,
                response_deserializer=compiler_dot_grpc_dot_proto_dot_event__pb2.FixtureEventsResponse.FromString,
                )


class EventServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FixtureEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FixtureEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.FixtureEvents,
                    request_deserializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.FixtureRequest.FromString,
                    response_serializer=compiler_dot_grpc_dot_proto_dot_event__pb2.FixtureEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FixtureEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.EventService/FixtureEvents',
            compiler_dot_grpc_dot_proto_dot_requests__pb2.FixtureRequest.SerializeToString,
            compiler_dot_grpc_dot_proto_dot_event__pb2.FixtureEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
