# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from compiler.grpc.proto import fixture_pb2 as compiler_dot_grpc_dot_proto_dot_fixture__pb2
from compiler.grpc.proto import requests_pb2 as compiler_dot_grpc_dot_proto_dot_requests__pb2


class FixtureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSeasonFixtures = channel.unary_stream(
                '/proto.FixtureService/ListSeasonFixtures',
                request_serializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.SeasonFixtureRequest.SerializeToString,
                response_deserializer=compiler_dot_grpc_dot_proto_dot_fixture__pb2.Fixture.FromString,
                )
        self.FixtureByID = channel.unary_unary(
                '/proto.FixtureService/FixtureByID',
                request_serializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.FixtureRequest.SerializeToString,
                response_deserializer=compiler_dot_grpc_dot_proto_dot_fixture__pb2.Fixture.FromString,
                )


class FixtureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListSeasonFixtures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FixtureByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FixtureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSeasonFixtures': grpc.unary_stream_rpc_method_handler(
                    servicer.ListSeasonFixtures,
                    request_deserializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.SeasonFixtureRequest.FromString,
                    response_serializer=compiler_dot_grpc_dot_proto_dot_fixture__pb2.Fixture.SerializeToString,
            ),
            'FixtureByID': grpc.unary_unary_rpc_method_handler(
                    servicer.FixtureByID,
                    request_deserializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.FixtureRequest.FromString,
                    response_serializer=compiler_dot_grpc_dot_proto_dot_fixture__pb2.Fixture.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.FixtureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FixtureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSeasonFixtures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.FixtureService/ListSeasonFixtures',
            compiler_dot_grpc_dot_proto_dot_requests__pb2.SeasonFixtureRequest.SerializeToString,
            compiler_dot_grpc_dot_proto_dot_fixture__pb2.Fixture.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FixtureByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.FixtureService/FixtureByID',
            compiler_dot_grpc_dot_proto_dot_requests__pb2.FixtureRequest.SerializeToString,
            compiler_dot_grpc_dot_proto_dot_fixture__pb2.Fixture.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
