# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compiler/grpc/proto/fixture.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from compiler.grpc.proto import common_pb2 as compiler_dot_grpc_dot_proto_dot_common__pb2
from compiler.grpc.proto import competition_pb2 as compiler_dot_grpc_dot_proto_dot_competition__pb2
from compiler.grpc.proto import requests_pb2 as compiler_dot_grpc_dot_proto_dot_requests__pb2
from compiler.grpc.proto import round_pb2 as compiler_dot_grpc_dot_proto_dot_round__pb2
from compiler.grpc.proto import season_pb2 as compiler_dot_grpc_dot_proto_dot_season__pb2
from compiler.grpc.proto import team_pb2 as compiler_dot_grpc_dot_proto_dot_team__pb2
from compiler.grpc.proto import venue_pb2 as compiler_dot_grpc_dot_proto_dot_venue__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='compiler/grpc/proto/fixture.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!compiler/grpc/proto/fixture.proto\x12\x05proto\x1a compiler/grpc/proto/common.proto\x1a%compiler/grpc/proto/competition.proto\x1a\"compiler/grpc/proto/requests.proto\x1a\x1f\x63ompiler/grpc/proto/round.proto\x1a compiler/grpc/proto/season.proto\x1a\x1e\x63ompiler/grpc/proto/team.proto\x1a\x1f\x63ompiler/grpc/proto/venue.proto\"\xf7\x01\n\x07\x46ixture\x12\n\n\x02id\x18\x01 \x01(\x03\x12\'\n\x0b\x63ompetition\x18\x02 \x01(\x0b\x32\x12.proto.Competition\x12\x1d\n\x06season\x18\x03 \x01(\x0b\x32\r.proto.Season\x12\x1e\n\thome_team\x18\x04 \x01(\x0b\x32\x0b.proto.Team\x12\x1e\n\taway_team\x18\x05 \x01(\x0b\x32\x0b.proto.Team\x12\x1b\n\x05round\x18\x06 \x01(\x0b\x32\x0c.proto.Round\x12\x1b\n\x05venue\x18\x07 \x01(\x0b\x32\x0c.proto.Venue\x12\x1e\n\tdate_time\x18\x08 \x01(\x0b\x32\x0b.proto.Date2\x8f\x01\n\x0e\x46ixtureService\x12\x45\n\x12ListSeasonFixtures\x12\x1b.proto.SeasonFixtureRequest\x1a\x0e.proto.Fixture\"\x00\x30\x01\x12\x36\n\x0b\x46ixtureByID\x12\x15.proto.FixtureRequest\x1a\x0e.proto.Fixture\"\x00\x62\x06proto3')
  ,
  dependencies=[compiler_dot_grpc_dot_proto_dot_common__pb2.DESCRIPTOR,compiler_dot_grpc_dot_proto_dot_competition__pb2.DESCRIPTOR,compiler_dot_grpc_dot_proto_dot_requests__pb2.DESCRIPTOR,compiler_dot_grpc_dot_proto_dot_round__pb2.DESCRIPTOR,compiler_dot_grpc_dot_proto_dot_season__pb2.DESCRIPTOR,compiler_dot_grpc_dot_proto_dot_team__pb2.DESCRIPTOR,compiler_dot_grpc_dot_proto_dot_venue__pb2.DESCRIPTOR,])




_FIXTURE = _descriptor.Descriptor(
  name='Fixture',
  full_name='proto.Fixture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Fixture.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='competition', full_name='proto.Fixture.competition', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='season', full_name='proto.Fixture.season', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='home_team', full_name='proto.Fixture.home_team', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='away_team', full_name='proto.Fixture.away_team', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round', full_name='proto.Fixture.round', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='venue', full_name='proto.Fixture.venue', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_time', full_name='proto.Fixture.date_time', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=533,
)

_FIXTURE.fields_by_name['competition'].message_type = compiler_dot_grpc_dot_proto_dot_competition__pb2._COMPETITION
_FIXTURE.fields_by_name['season'].message_type = compiler_dot_grpc_dot_proto_dot_season__pb2._SEASON
_FIXTURE.fields_by_name['home_team'].message_type = compiler_dot_grpc_dot_proto_dot_team__pb2._TEAM
_FIXTURE.fields_by_name['away_team'].message_type = compiler_dot_grpc_dot_proto_dot_team__pb2._TEAM
_FIXTURE.fields_by_name['round'].message_type = compiler_dot_grpc_dot_proto_dot_round__pb2._ROUND
_FIXTURE.fields_by_name['venue'].message_type = compiler_dot_grpc_dot_proto_dot_venue__pb2._VENUE
_FIXTURE.fields_by_name['date_time'].message_type = compiler_dot_grpc_dot_proto_dot_common__pb2._DATE
DESCRIPTOR.message_types_by_name['Fixture'] = _FIXTURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fixture = _reflection.GeneratedProtocolMessageType('Fixture', (_message.Message,), dict(
  DESCRIPTOR = _FIXTURE,
  __module__ = 'compiler.grpc.proto.fixture_pb2'
  # @@protoc_insertion_point(class_scope:proto.Fixture)
  ))
_sym_db.RegisterMessage(Fixture)



_FIXTURESERVICE = _descriptor.ServiceDescriptor(
  name='FixtureService',
  full_name='proto.FixtureService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=536,
  serialized_end=679,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListSeasonFixtures',
    full_name='proto.FixtureService.ListSeasonFixtures',
    index=0,
    containing_service=None,
    input_type=compiler_dot_grpc_dot_proto_dot_requests__pb2._SEASONFIXTUREREQUEST,
    output_type=_FIXTURE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FixtureByID',
    full_name='proto.FixtureService.FixtureByID',
    index=1,
    containing_service=None,
    input_type=compiler_dot_grpc_dot_proto_dot_requests__pb2._FIXTUREREQUEST,
    output_type=_FIXTURE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIXTURESERVICE)

DESCRIPTOR.services_by_name['FixtureService'] = _FIXTURESERVICE

# @@protoc_insertion_point(module_scope)
