# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from compiler.grpc.proto import requests_pb2 as compiler_dot_grpc_dot_proto_dot_requests__pb2
from compiler.grpc.proto import team_pb2 as compiler_dot_grpc_dot_proto_dot_team__pb2


class TeamServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTeamByID = channel.unary_unary(
        '/proto.TeamService/GetTeamByID',
        request_serializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.TeamRequest.SerializeToString,
        response_deserializer=compiler_dot_grpc_dot_proto_dot_team__pb2.Team.FromString,
        )
    self.GetTeamsBySeasonId = channel.unary_stream(
        '/proto.TeamService/GetTeamsBySeasonId',
        request_serializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.SeasonTeamsRequest.SerializeToString,
        response_deserializer=compiler_dot_grpc_dot_proto_dot_team__pb2.Team.FromString,
        )


class TeamServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTeamByID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTeamsBySeasonId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TeamServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTeamByID': grpc.unary_unary_rpc_method_handler(
          servicer.GetTeamByID,
          request_deserializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.TeamRequest.FromString,
          response_serializer=compiler_dot_grpc_dot_proto_dot_team__pb2.Team.SerializeToString,
      ),
      'GetTeamsBySeasonId': grpc.unary_stream_rpc_method_handler(
          servicer.GetTeamsBySeasonId,
          request_deserializer=compiler_dot_grpc_dot_proto_dot_requests__pb2.SeasonTeamsRequest.FromString,
          response_serializer=compiler_dot_grpc_dot_proto_dot_team__pb2.Team.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.TeamService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
