# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predictor/grpc/proto/fixture/fixture.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from predictor.grpc.proto.competition import competition_pb2 as predictor_dot_grpc_dot_proto_dot_competition_dot_competition__pb2
from predictor.grpc.proto.season import season_pb2 as predictor_dot_grpc_dot_proto_dot_season_dot_season__pb2
from predictor.grpc.proto.team import team_pb2 as predictor_dot_grpc_dot_proto_dot_team_dot_team__pb2
from predictor.grpc.proto.venue import venue_pb2 as predictor_dot_grpc_dot_proto_dot_venue_dot_venue__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='predictor/grpc/proto/fixture/fixture.proto',
  package='fixture',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*predictor/grpc/proto/fixture/fixture.proto\x12\x07\x66ixture\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x32predictor/grpc/proto/competition/competition.proto\x1a(predictor/grpc/proto/season/season.proto\x1a$predictor/grpc/proto/team/team.proto\x1a&predictor/grpc/proto/venue/venue.proto\"6\n\x10\x44\x61teRangeRequest\x12\x11\n\tdate_from\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61te_to\x18\x02 \x01(\t\"$\n\x0e\x46ixtureRequest\x12\x12\n\nfixture_id\x18\x01 \x01(\x03\"\x83\x02\n\x07\x46ixture\x12\n\n\x02id\x18\x01 \x01(\x03\x12-\n\x0b\x63ompetition\x18\x02 \x01(\x0b\x32\x18.competition.Competition\x12\x1e\n\x06season\x18\x03 \x01(\x0b\x32\x0e.season.Season\x12\x1d\n\thome_team\x18\x04 \x01(\x0b\x32\n.team.Team\x12\x1d\n\taway_team\x18\x05 \x01(\x0b\x32\n.team.Team\x12\x1b\n\x05venue\x18\x06 \x01(\x0b\x32\x0c.venue.Venue\x12/\n\nreferee_id\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x11\n\tdate_time\x18\x08 \x01(\x03\x32\x8d\x01\n\x0e\x46ixtureService\x12?\n\x0cListFixtures\x12\x19.fixture.DateRangeRequest\x1a\x10.fixture.Fixture\"\x00\x30\x01\x12:\n\x0b\x46ixtureByID\x12\x17.fixture.FixtureRequest\x1a\x10.fixture.Fixture\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,predictor_dot_grpc_dot_proto_dot_competition_dot_competition__pb2.DESCRIPTOR,predictor_dot_grpc_dot_proto_dot_season_dot_season__pb2.DESCRIPTOR,predictor_dot_grpc_dot_proto_dot_team_dot_team__pb2.DESCRIPTOR,predictor_dot_grpc_dot_proto_dot_venue_dot_venue__pb2.DESCRIPTOR,])




_DATERANGEREQUEST = _descriptor.Descriptor(
  name='DateRangeRequest',
  full_name='fixture.DateRangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_from', full_name='fixture.DateRangeRequest.date_from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_to', full_name='fixture.DateRangeRequest.date_to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=313,
)


_FIXTUREREQUEST = _descriptor.Descriptor(
  name='FixtureRequest',
  full_name='fixture.FixtureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fixture_id', full_name='fixture.FixtureRequest.fixture_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=351,
)


_FIXTURE = _descriptor.Descriptor(
  name='Fixture',
  full_name='fixture.Fixture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fixture.Fixture.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='competition', full_name='fixture.Fixture.competition', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='season', full_name='fixture.Fixture.season', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='home_team', full_name='fixture.Fixture.home_team', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='away_team', full_name='fixture.Fixture.away_team', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='venue', full_name='fixture.Fixture.venue', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referee_id', full_name='fixture.Fixture.referee_id', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_time', full_name='fixture.Fixture.date_time', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=613,
)

_FIXTURE.fields_by_name['competition'].message_type = predictor_dot_grpc_dot_proto_dot_competition_dot_competition__pb2._COMPETITION
_FIXTURE.fields_by_name['season'].message_type = predictor_dot_grpc_dot_proto_dot_season_dot_season__pb2._SEASON
_FIXTURE.fields_by_name['home_team'].message_type = predictor_dot_grpc_dot_proto_dot_team_dot_team__pb2._TEAM
_FIXTURE.fields_by_name['away_team'].message_type = predictor_dot_grpc_dot_proto_dot_team_dot_team__pb2._TEAM
_FIXTURE.fields_by_name['venue'].message_type = predictor_dot_grpc_dot_proto_dot_venue_dot_venue__pb2._VENUE
_FIXTURE.fields_by_name['referee_id'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT64VALUE
DESCRIPTOR.message_types_by_name['DateRangeRequest'] = _DATERANGEREQUEST
DESCRIPTOR.message_types_by_name['FixtureRequest'] = _FIXTUREREQUEST
DESCRIPTOR.message_types_by_name['Fixture'] = _FIXTURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DateRangeRequest = _reflection.GeneratedProtocolMessageType('DateRangeRequest', (_message.Message,), dict(
  DESCRIPTOR = _DATERANGEREQUEST,
  __module__ = 'predictor.grpc.proto.fixture.fixture_pb2'
  # @@protoc_insertion_point(class_scope:fixture.DateRangeRequest)
  ))
_sym_db.RegisterMessage(DateRangeRequest)

FixtureRequest = _reflection.GeneratedProtocolMessageType('FixtureRequest', (_message.Message,), dict(
  DESCRIPTOR = _FIXTUREREQUEST,
  __module__ = 'predictor.grpc.proto.fixture.fixture_pb2'
  # @@protoc_insertion_point(class_scope:fixture.FixtureRequest)
  ))
_sym_db.RegisterMessage(FixtureRequest)

Fixture = _reflection.GeneratedProtocolMessageType('Fixture', (_message.Message,), dict(
  DESCRIPTOR = _FIXTURE,
  __module__ = 'predictor.grpc.proto.fixture.fixture_pb2'
  # @@protoc_insertion_point(class_scope:fixture.Fixture)
  ))
_sym_db.RegisterMessage(Fixture)



_FIXTURESERVICE = _descriptor.ServiceDescriptor(
  name='FixtureService',
  full_name='fixture.FixtureService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=616,
  serialized_end=757,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListFixtures',
    full_name='fixture.FixtureService.ListFixtures',
    index=0,
    containing_service=None,
    input_type=_DATERANGEREQUEST,
    output_type=_FIXTURE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FixtureByID',
    full_name='fixture.FixtureService.FixtureByID',
    index=1,
    containing_service=None,
    input_type=_FIXTUREREQUEST,
    output_type=_FIXTURE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIXTURESERVICE)

DESCRIPTOR.services_by_name['FixtureService'] = _FIXTURESERVICE

# @@protoc_insertion_point(module_scope)
