# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compiler/grpc/proto/requests/requests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compiler/grpc/proto/requests/requests.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+compiler/grpc/proto/requests/requests.proto\x12\x05proto\"$\n\x0e\x46ixtureRequest\x12\x12\n\nfixture_id\x18\x01 \x01(\x04\"M\n\x14SeasonFixtureRequest\x12\x11\n\tseason_id\x18\x01 \x01(\x04\x12\x11\n\tdate_from\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x61te_to\x18\x03 \x01(\tb\x06proto3')
)




_FIXTUREREQUEST = _descriptor.Descriptor(
  name='FixtureRequest',
  full_name='proto.FixtureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fixture_id', full_name='proto.FixtureRequest.fixture_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=90,
)


_SEASONFIXTUREREQUEST = _descriptor.Descriptor(
  name='SeasonFixtureRequest',
  full_name='proto.SeasonFixtureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='season_id', full_name='proto.SeasonFixtureRequest.season_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_from', full_name='proto.SeasonFixtureRequest.date_from', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_to', full_name='proto.SeasonFixtureRequest.date_to', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['FixtureRequest'] = _FIXTUREREQUEST
DESCRIPTOR.message_types_by_name['SeasonFixtureRequest'] = _SEASONFIXTUREREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FixtureRequest = _reflection.GeneratedProtocolMessageType('FixtureRequest', (_message.Message,), dict(
  DESCRIPTOR = _FIXTUREREQUEST,
  __module__ = 'compiler.grpc.proto.requests.requests_pb2'
  # @@protoc_insertion_point(class_scope:proto.FixtureRequest)
  ))
_sym_db.RegisterMessage(FixtureRequest)

SeasonFixtureRequest = _reflection.GeneratedProtocolMessageType('SeasonFixtureRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEASONFIXTUREREQUEST,
  __module__ = 'compiler.grpc.proto.requests.requests_pb2'
  # @@protoc_insertion_point(class_scope:proto.SeasonFixtureRequest)
  ))
_sym_db.RegisterMessage(SeasonFixtureRequest)


# @@protoc_insertion_point(module_scope)
